version: "3.9"

services:
  face-recognition-api:
    image: face-recognition-api
    container_name: face-recognition-api
    ports:
      - "6969:8000"
    environment:
      DB_PATH: /storage/embeddings.db
      API_KEY: ${API_KEY}
    volumes:
      - ./storage:/storage
    restart: unless-stopped
    networks:
      - web-network

networks:
  web-network:
    name: web-network
    external: true
