version: "3.9"

services:
  face-recognition-api:
    build: .
    container_name: face-recognition-api
    ports:
      - "6969:8000"
    environment:
      DB_PATH: /storage/embeddings.db
      API_KEY: ${API_KEY}
    volumes:
      - ./storage:/storage
    restart: unless-stopped
    networks:
      - web-network
    deploy:
      resources:
        limits:
          cpus: '4.0'      # Maksimal menggunakan 2 Core CPU
          memory: 4096M    # Maksimal menggunakan 4 GB RAM
  
networks:
  web-network:
    name: web-network
    external: true
